


# - name: Checking {{current_cp4waiops_feature.kind}}
#   debug:
#     var: current_cp4waiops_feature




- name: CHECK for - AI Manager
  include_role:
    name: cp4waiops-ai-manager
  when: current_cp4waiops_feature.kind=="AIManager" and current_cp4waiops_feature.install==true


- name: CHECK for - AI Manager Demo Content
  include_role:
    name: cp4waiops-ai-manager-demo-content
  when: current_cp4waiops_feature.kind=="AIManagerDemoContent" and current_cp4waiops_feature.install==true


- name: CHECK for - Event Manager
  include_role:
    name: cp4waiops-event-manager
  when: current_cp4waiops_feature.kind=="EventManager" and current_cp4waiops_feature.install==true


- name: CHECK for - Infrastructure Management
  include_role:
    name: cp4waiops-infrastructure-management
  when: current_cp4waiops_feature.kind=="InfrastructureManagement" and current_cp4waiops_feature.install==true


- name: CHECK for - ELK Stack
  include_role:
    name: cp4waiops-elk
  when: current_cp4waiops_feature.kind=="ELK" and current_cp4waiops_feature.install==true


- name: CHECK for - Turbonomic
  include_role:
    name: cp4waiops-turbonomic
  when: current_cp4waiops_feature.kind=="Turbonomic" and current_cp4waiops_feature.install==true
