
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Install ADDONS
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

# --------------------------------------------------------------------------------------------------------------------------------------
# Install OpenLDAP
# --------------------------------------------------------------------------------------------------------------------------------------

- name: üõ∞Ô∏è START - PREREQUISITES - INSTALL OPENLDAP
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: üì• WRITE TO LOGFILE
  shell: |
    export MESSAGE="Installing Open LDAP"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes



# - name: ADDONS -             ‚ùé Remove old OpenLDAP
#   kubernetes.core.k8s:
#     state: absent
#     template: ./templates/ldap/install-ldap.j2
#   #when: INSTALL_LDAP == true

- name: LDAP -                   üöÄ Install OpenLDAP
  kubernetes.core.k8s:
    state: present
    template: ./templates/ldap/install-ldap.j2
  #when: INSTALL_LDAP == true



- name: TIMESTAMP -              ‚úÖ END INSTALLATION - INSTALL OPENLDAP
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"

