
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patches
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

- name: TIMESTAMP -              ðŸŸ¢ START - CREATE ROUTES
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: ROUTES -                 ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Create External Routes"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes


# --------------------------------------------------------------------------------------------------------------------------------------
# Patch Ingress
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ROUTES -                 ðŸ©¹ Patch Ingress policy-group
  shell: oc patch namespace default --type=json -p '[{"op":"add","path":"/metadata/labels","value":{"network.openshift.io/policy-group":"ingress"}}]'
  register: ingress_patched


# - name: HACK    -             ðŸ©¹ Patch AIOpsAnalyticsOrchestrator Pull Secret
#   shell: oc patch AIOpsAnalyticsOrchestrator aiops -n {{current_cp4waiops_cluster.project}} --type merge  --patch-file ./templates/waiops/patches/analytics-pull-patch.yaml
#   ignore_errors: yes
#   register: irorchestrator_patched



# --------------------------------------------------------------------------------------------------------------------------------------
# Create Topology Routes
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ROUTES -               ðŸ”Ž Check Topology Routes
  shell: |
    oc get route --ignore-not-found -n {{current_cp4waiops_cluster.project}} topology-merge
  ignore_errors: yes
  register: OBJECT_EXISTS



- name: ROUTES -                 ðŸš€ Create Topology Routes
  block:
  - name: ROUTES -                 ðŸš€ Create Topology Route - topology-merge
    shell: oc create route passthrough topology-merge -n {{current_cp4waiops_cluster.project}} --insecure-policy="Redirect" --service=aiops-topology-merge --port=https-merge-api
    ignore_errors: yes
    when: create_topo_route == true

  - name: ROUTES -                 ðŸš€ Create Topology Route - topology-rest
    shell: oc create route passthrough topology-rest -n {{current_cp4waiops_cluster.project}} --insecure-policy="Redirect" --service=aiops-topology-rest-observer --port=https-rest-observer-admin
    ignore_errors: yes
    when: create_topo_route == true

  - name: ROUTES -                 ðŸš€ Create Topology Route - topology-file
    shell: oc create route passthrough topology-file -n {{current_cp4waiops_cluster.project}} --insecure-policy="Redirect" --service=aiops-topology-file-observer --port=https-file-observer-admin
    ignore_errors: yes
    when: create_topo_route == true

  - name: ROUTES -                 ðŸš€ Create Topology Route - topology-manage
    shell: oc create route passthrough topology-manage -n {{current_cp4waiops_cluster.project}} --service=aiops-topology-topology --port=https-topology-api
    ignore_errors: yes
    when: create_topo_route == true

  - name: ROUTES -                 ðŸš€ Create Topology Route - topology-file-api
    shell: oc create route reencrypt topology-file-api -n {{current_cp4waiops_cluster.project}} --service=aiops-topology-file-observer --port=https-file-observer-api
    ignore_errors: yes
    when: create_topo_route == true

  when: OBJECT_EXISTS.stdout|length == 0




- name: ROUTES -                 ðŸš€ Create external Routes
  block:
  - name: ROUTES -                 ðŸš€ Create external Flink Job Manager Route (you can ignore errors in this step)
    shell: oc create route edge job-manager -n {{current_cp4waiops_cluster.project}} --service=cp4waiops-eventprocessor-eve-29ee-ep-jobmanager --port=ui
    ignore_errors: yes
    when: create_external_routes == true
  
  - name: ROUTES -                 ðŸš€ Create external Flink Policy Job Manager Route (you can ignore errors in this step)
    shell: oc create route edge job-manager-policy -n {{current_cp4waiops_cluster.project}} --service=aiops-ir-lifecycle-eventprocessor-ep-jobmanager --port=ui
    ignore_errors: yes






  - name: ROUTES -                 ðŸš€ Create external AI Manager API Route (you can ignore errors in this step)
    shell: oc create route passthrough ai-platform-api -n {{current_cp4waiops_cluster.project}}  --service=aimanager-aio-ai-platform-api-server --port=4000 --insecure-policy=Redirect --wildcard-policy=None
    ignore_errors: yes
    when: create_external_routes == true


  - name: ROUTES -                 ðŸš€ Create external Datalayer API Route (you can ignore errors in this step)
    shell: oc create route reencrypt datalayer-api -n {{current_cp4waiops_cluster.project}}  --service=aiops-ir-core-ncodl-api --port=secure-port --insecure-policy=Redirect --wildcard-policy=None
    ignore_errors: yes
    when: create_external_routes == true


  - name: ROUTES -                 ðŸš€ Create external AIO Controller Route (you can ignore errors in this step)
    shell: oc create route passthrough aimanager-aio-controller -n {{current_cp4waiops_cluster.project}}  --service=aimanager-aio-controller
    ignore_errors: yes
    when: create_external_routes == true


  - name: ROUTES -                 ðŸš€ Enable Swagger on external Datalayer API Route (you can ignore errors in this step)
    shell: oc set env deploy -n {{current_cp4waiops_cluster.project}} aiops-ir-core-ncodl-api ENABLE_SWAGGER_UI="true" 
    ignore_errors: yes
    when: create_external_routes == true

  # - name: ROUTES -                 ðŸš€ Create Spark Master UI Route (you can ignore errors in this step)
  #   shell: oc expose svc aiops-ir-analytics-spark-master -n {{current_cp4waiops_cluster.project}} --name spark
  #   ignore_errors: yes
  #   when: create_external_routes == true


# # --------------------------------------------------------------------------------------------------------------------------------------
# # Wait for Cassandra Pod
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ•¦ Wait for Cassandra Pod to become available - this can take up to 45 minutes (hack for v3.4.0)
#   shell: oc get po -n {{current_cp4waiops_cluster.project}} | grep aiops-topology-cassandra-0| grep 1/1| grep -c ""
#   register: kubectl_get_pods
#   until: kubectl_get_pods.stdout == "1"
#   retries: 500
#   delay: 15


# # --------------------------------------------------------------------------------------------------------------------------------------
# # Patch Service Account
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ©¹ Patch aiops-topology-service-account (hack for v3.4.0)
#   shell: |
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-topology-service-account -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#   ignore_errors: yes


  

# # --------------------------------------------------------------------------------------------------------------------------------------
# # Wait for Topology Pods
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ•¦ Wait for Topology Pods to become available - this can take up to 45 minutes (hack for v3.4.0)
#   shell: oc get po -n {{current_cp4waiops_cluster.project}} | grep aiops-topology-merge| grep -c ""
#   register: kubectl_get_pods
#   until: kubectl_get_pods.stdout == "1"
#   retries: 500
#   delay: 15


# # --------------------------------------------------------------------------------------------------------------------------------------
# # Patch Topology Pods
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ©¹ Patch aiops-topology-merge (hack for v3.4.0)
#   shell: oc patch deployment aiops-topology-merge -n {{current_cp4waiops_cluster.project}} --patch-file ./templates/waiops/patches/aiops-topology-merge-patch.yaml
#   ignore_errors: yes


# - name: HACK    -             ðŸ©¹ Patch aiops-topology-search (hack for v3.4.0)
#   shell: oc patch deployment aiops-topology-search -n {{current_cp4waiops_cluster.project}} --patch-file ./templates/waiops/patches/aiops-topology-search-patch.yaml
#   ignore_errors: yes


# - name: HACK    -             ðŸ©¹ Patch aiops-topology-status (hack for v3.4.0)
#   shell: oc patch deployment aiops-topology-status -n {{current_cp4waiops_cluster.project}} --patch-file ./templates/waiops/patches/aiops-topology-status-patch.yaml
#   ignore_errors: yes


# - name: HACK    -             ðŸ©¹ Patch aiops-topology-layout (hack for v3.4.0)
#   shell: oc patch deployment aiops-topology-layout -n {{current_cp4waiops_cluster.project}} --patch-file ./templates/waiops/patches/aiops-topology-layout-patch.yaml
#   ignore_errors: yes


# # --------------------------------------------------------------------------------------------------------------------------------------
# # Wait for IR Analytics Pods
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ•¦ Wait for IR Analytics Pods to become available - this can take up to 45 minutes (hack for v3.4.0)
#   shell: oc get po -n {{current_cp4waiops_cluster.project}} | grep aiops-ir-analytics-|grep -c ""
#   register: kubectl_get_pods
#   until: kubectl_get_pods.stdout > "4"
#   retries: 500
#   delay: 15


# # --------------------------------------------------------------------------------------------------------------------------------------
# # Patch IR Analytics Pods
# # --------------------------------------------------------------------------------------------------------------------------------------
# - name: HACK    -             ðŸ©¹ Patch IR Analytics Pods (hack for v3.4.0) (you can ignore errors in this step)
#   shell: |
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-topology-service-account -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-analytics-spark-worker -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-analytics-spark-pipeline-composer -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-analytics-spark-master -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-analytics-probablecause -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-analytics-classifier -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc patch -n {{current_cp4waiops_cluster.project}} serviceaccount aiops-ir-lifecycle-eventprocessor-ep -p '{"imagePullSecrets": [{"name": "ibm-entitlement-key"}]}'
#     oc delete pod $(oc get po -n {{current_cp4waiops_cluster.project}}|grep ImagePull|awk '{print$1}') -n {{current_cp4waiops_cluster.project}}
#   ignore_errors: yes


# --------------------------------------------------------------------------------------------------------------------------------------
# Delete ImgPull error pods
# --------------------------------------------------------------------------------------------------------------------------------------
- name: ROUTES -                 ðŸ©¹ Delete Pods with ImgPull Error  (you can ignore errors in this step)
  shell: |
        errorPods=$(oc get po -n {{current_cp4waiops_cluster.project}}|grep ImagePull|awk '{print$1}')
        if [[ ! $errorPods == "" ]]; then
          echo "Refreshing Pods"
          oc delete pod --ignore-not-found $(oc get po -n {{current_cp4waiops_cluster.project}}|grep ImagePull|awk '{print$1}') -n {{current_cp4waiops_cluster.project}}>/dev/null 2>/dev/null
        fi


  ignore_errors: yes
