

- name: TIMESTAMP -              ðŸŸ¢ START - INSTALL AI MANAGER RUNBOOKS
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: AIManager Runbook -      ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Load AI Manager Runbooks"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes


- name: AIManager Runbook -      ðŸŒ Get ZEN TOKEN
  shell: |
    ZEN_API_HOST=$(oc get route -n {{current_cp4waiops_cluster.project}} cpd -o jsonpath='{.spec.host}')
    ZEN_LOGIN_URL="https://${ZEN_API_HOST}/v1/preauth/signin"
    LOGIN_USER=admin
    LOGIN_PASSWORD="$(oc get secret admin-user-details -n {{current_cp4waiops_cluster.project}} -o jsonpath='{ .data.initial_admin_password }' | base64 --decode)"

    ZEN_LOGIN_RESPONSE=$(
    curl -k \
    -H 'Content-Type: application/json' \
    -XPOST \
    "${ZEN_LOGIN_URL}" \
    -d '{
          "username": "'"${LOGIN_USER}"'",
          "password": "'"${LOGIN_PASSWORD}"'"
    }' 2> /dev/null
    )

    ZEN_TOKEN=$(echo "${ZEN_LOGIN_RESPONSE}" | jq -r .token)
    echo $ZEN_TOKEN

    export ROUTE=$(oc get route -n $WAIOPS_NAMESPACE cpd -o jsonpath={.spec.host})
    echo "ROUTE:$ROUTE"
    export result=$(curl -X "GET" -k "https://$ROUTE/aiops/api/story-manager/rba/v1/runbooks" \
          -H "Authorization: bearer $ZEN_TOKEN" \
          -H 'Content-Type: application/json; charset=utf-8' )

    echo "RESULT:$result"

    export MY_RUNBOOK_ID=$(echo $result| sed 's/\\\\"/\\"/g'|jq -r '.[]| select(.name|contains("Mitigate"))|._runbookId'| head -n 1)
    echo "RUNBOOK_ID: $MY_RUNBOOK_ID"


    # Create Runbook Trigger Policy
    export POLICY_FILE="{{role_path}}/templates/policies/runbook-trigger-policy.json"
    echo $POLICY_FILE
    
    cp $POLICY_FILE /tmp/runbook_policy.json

    sed -i -e "s/MY_RUNBOOK_ID/$MY_RUNBOOK_ID/g" /tmp/runbook_policy.json


  ignore_errors: yes
  register: POLICY_RESULT
  args:
    executable: /bin/bash

- name: DEBUG -                 ðŸŸ¢ Output
  debug: 
    var: POLICY_RESULT.stdout_lines


