

- name: ðŸ›°ï¸ START - PREREQUISITES - LOAD METRIC TRAINING DATA
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"


- name: ðŸ“¥ WRITE TO LOGFILE
  shell: |
    export MESSAGE="Load Metric Training Data into Cassandra"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes


- name: TRAINING LOAD METRIC -   ðŸš€ CREATE CLUSTERROLE
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/default-clusterrole.yaml
    

- name: TRAINING LOAD METRIC -   ðŸš€ LOAD CASSANDRA METRIC DATA 
  kubernetes.core.k8s:
    state: present
    namespace: default
    src: ./templates/training/load-job-metric.yaml
  