- name: TIMESTAMP -              üõ∞Ô∏è START - RUN METRIC TRAINING
  debug: 
    msg="{{ lookup('pipe','date +%d.%m.%Y---%H:%M:%S') }}"




- name: TRAINING RUN -       üì• WRITE TO LOGFILE
  shell: |
    export MESSAGE="Run Metrics Training"
    export currentDate=$(date +%Y-%m-%d_%H:%M)
    echo "---------------------------------------------------------------------------------------------------------------------------------------------------" >> ../install_{{current_cp4waiops_feature.kind}}.log
    echo $currentDate" - "$USER" - "$MESSAGE  >> ../install_{{current_cp4waiops_feature.kind}}.log
  ignore_errors: yes



- name: TRAINING RUN -           üöÄ RUN TRAINING METRIC
  shell: |
    set -x
    
    echo "  ***************************************************************************************************************************************************"
    echo "   üõ†Ô∏è  Run Analysis: MEtricAnomaly"
    export FILE_NAME=run-analysis-METRIC.graphql
    export FILE_PATH="{{role_path}}/templates/training/training-definitions/"
    {{role_path}}/templates/training/scripts/execute-graphql.sh


  register: output_string
  ignore_errors: yes
  args:
    executable: /bin/bash


- name: TRAINING RUN METRIC -       ‚úÖ RESULT
  debug: 
    var: output_string.stdout_lines
  #when: PRINT_LOGINS == true

